# Generated by Django 4.2.7 on 2025-10-27 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('credential_type', models.CharField(choices=[('ssh_key', 'SSH Key'), ('kubeconfig', 'Kubeconfig')], max_length=20)),
                ('content', models.TextField(help_text='SSH private key or kubeconfig content')),
                ('username', models.CharField(blank=True, help_text='SSH username (only for SSH keys)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('host_type', models.CharField(choices=[('baremetal', 'Baremetal/VM'), ('k8s_pod', 'Kubernetes Pod')], max_length=20)),
                ('hostname', models.CharField(help_text='IP/hostname for baremetal, pod name for K8s', max_length=255)),
                ('port', models.IntegerField(default=22, help_text='SSH port (only for baremetal)')),
                ('namespace', models.CharField(blank=True, help_text='K8s namespace (only for pods)', max_length=255, null=True)),
                ('container', models.CharField(blank=True, help_text='K8s container name (optional)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_credential', models.ForeignKey(blank=True, help_text='Default credential for this host', null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminal.credential')),
            ],
        ),
    ]
